[project]
name = "sentiment_analysis_backend"
version = "0.1.0"
description = "A backend service for sentiment analysis."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "sqlalchemy>=2.0.45",
]
